name: amls-final
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - medmnist